pcoError.pyd,sha256=zoFTU-Z0QaR_8rZUrtqzl3HxVHqhGzgcf5y0ldbHnAA,17408
pydicamsdk-0.1.0.dist-info/DESCRIPTION.rst,sha256=OCTuuN6LcWulhHS3d5rfjdsQtW22n7HENFRh6jC6ego,10
pydicamsdk-0.1.0.dist-info/METADATA,sha256=dafxjz4PqOKeysbegQ9cR9LGHmqYd7MI-X1Pz7HxgGc,345
pydicamsdk-0.1.0.dist-info/metadata.json,sha256=2n2S8lUa2rcqDLOyOeqFEcnuEPP91kWBrpw6kao1pRc,552
pydicamsdk-0.1.0.dist-info/RECORD,,
pydicamsdk-0.1.0.dist-info/top_level.txt,sha256=vy9gYqfJci7_VeLF42cqi1Tbdnkth-ePXKIFsSuRi_0,9
pydicamsdk-0.1.0.dist-info/WHEEL,sha256=KnbTkCSk5TbePQmBkhj7xCytA_auHPYSO_0D49rerQM,105
