# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-08-06 15:20-0500\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../testdrive-gtk.desktop.in.h:1
msgid "Test Drive an Ubuntu ISO"
msgstr ""

#: ../testdrive-gtk.desktop.in.h:2
msgid "Download and run an Ubuntu ISO in a Virtual Machine"
msgstr ""

#: ../testdrive-gtk.desktop.in.h:3
msgid "ISO;Testing;Ubuntu;Daily;VM;Virtual Machine;zsync;rsync;Testdrive"
msgstr ""

#: ../bin/testdrive-gtk.py:55
msgid "Other"
msgstr ""

#. ##################################################################
#. ####### Obtaining the settings from the Preferences Class ########
#. ##################################################################
#: ../bin/testdrive-gtk.py:145
msgid "Instancing Preferences..."
msgstr ""

#: ../bin/testdrive-gtk.py:228
#, python-format
msgid ""
"Checking available ISOs at the ISO tracker [http://iso.qa.ubuntu.com] every "
"%s seconds"
msgstr ""

#: ../bin/testdrive-gtk.py:233
msgid "Unable to check the ISO tracker"
msgstr ""

#: ../bin/testdrive-gtk.py:271
#, python-format
msgid "<b>Release:</b> %s"
msgstr ""

#: ../bin/testdrive-gtk.py:272
#, python-format
msgid "<b>ISO Repository:</b> http://%s.ubuntu.com/"
msgstr ""

#: ../bin/testdrive-gtk.py:312
msgid "Add an ISO to TestDrive"
msgstr ""

#: ../bin/testdrive-gtk.py:328
msgid ""
"Unable to open because 'testdrive' is not installed.\n"
"Please install testdrive: \n"
"\n"
"sudo apt-get install testdrive-cli"
msgstr ""

#: ../bin/testdrive-gtk.py:332
msgid "TestDrive an ISO or Disk Image"
msgstr ""

#. ##################################################################
#. ## Obtains the command for the Sync process based on Protocol ####
#. ##################################################################
#: ../bin/testdrive-gtk.py:407
msgid "Obtaining the sync protocol for the specified ISO..."
msgstr ""

#: ../bin/testdrive-gtk.py:410 ../bin/testdrive.py:379
#, python-format
msgid "Unsupported protocol [%s]"
msgstr ""

#. ##################################################################
#. #### Obtains the Virtualization Method, if not shows warnings ####
#. ##################################################################
#. Choose the virtualization engine
#: ../bin/testdrive-gtk.py:421
msgid "Obtaining the virtualization method..."
msgstr ""

#: ../bin/testdrive-gtk.py:425
msgid "Your CPU supports KVM acceleration; please install KVM"
msgstr ""

#: ../bin/testdrive-gtk.py:426
msgid ""
"Your CPU supports KVM acceleration; please install KVM:\n"
"\n"
"sudo apt-get install qemu-kvm"
msgstr ""

#: ../bin/testdrive-gtk.py:430
msgid ""
"Your CPU does not support acceleration; run kvm-ok for more information; "
"then install VBox"
msgstr ""

#: ../bin/testdrive-gtk.py:431
msgid ""
"Your CPU does not support acceleration; run kvm-ok for more information;\n"
"then please install VirtualBox\n"
"\n"
"kvm-ok\n"
"sudo apt-get install virtualbox"
msgstr ""

#. ##################################################################
#. ### Obtains the list of ISO available from the iso list cache ####
#. ##################################################################
#. Try to retrieve the ISO list from the cache
#: ../bin/testdrive-gtk.py:444 ../bin/testdrive.py:352
msgid "Retrieving the Ubuntu ISO list from cache..."
msgstr ""

#: ../bin/testdrive-gtk.py:448 ../bin/testdrive-gtk.py:449
#: ../bin/testdrive.py:356
msgid "Unable to retrieve the Ubuntu ISO list from cache..."
msgstr ""

#: ../bin/testdrive-gtk.py:569 ../bin/testdrive-gtk.py:604
#: ../bin/testdrive-gtk.py:919
#, python-format
msgid "<i>     CACHE: [%s]</i>"
msgstr ""

#: ../bin/testdrive-gtk.py:571 ../bin/testdrive-gtk.py:606
#: ../bin/testdrive-gtk.py:921
msgid "<i>     CACHE: [empty]</i>"
msgstr ""

#: ../bin/testdrive-gtk.py:634
msgid "<b><i>There are no Other ISOs yet...</i></b>"
msgstr ""

#: ../bin/testdrive-gtk.py:637
msgid "<b><i>There are no ISOs for this architecture yet...</i></b>"
msgstr ""

#. Add Button
#: ../bin/testdrive-gtk.py:671
msgid "Add ISO"
msgstr ""

#. Create Buttons
#: ../bin/testdrive-gtk.py:678
msgid "Create USB Disk"
msgstr ""

#: ../bin/testdrive-gtk.py:683
msgid "Sync"
msgstr ""

#: ../bin/testdrive-gtk.py:688
msgid "Launch"
msgstr ""

#: ../bin/testdrive-gtk.py:742 ../bin/testdrive.py:268
msgid "Using KVM for virtual machine hosting..."
msgstr ""

#: ../bin/testdrive-gtk.py:745 ../bin/testdrive.py:270
msgid "Using VirtualBox for virtual machine hosting..."
msgstr ""

#: ../bin/testdrive-gtk.py:748 ../bin/testdrive.py:272
msgid "Using Parallels Desktop for virtual machine hosting..."
msgstr ""

#: ../bin/testdrive-gtk.py:801
msgid "sync_iso: Thread is executing..."
msgstr ""

#: ../bin/testdrive-gtk.py:822
msgid "launch_iso: Thread is executing or syncing..."
msgstr ""

#: ../bin/testdrive-gtk.py:829
msgid ""
"No ISO has been selected.\n"
"\n"
"Please select an ISO to create an USB Startup Disk."
msgstr ""

#: ../bin/testdrive-gtk.py:834
msgid ""
"More than 1 ISO has been selected.\n"
"\n"
"Please select only 1 ISO to continue!"
msgstr ""

#: ../bin/testdrive-gtk.py:839
msgid ""
"The specified ISO does not exist!\n"
"\n"
"Please, synchronize the ISO to continue."
msgstr ""

#: ../bin/testdrive-gtk.py:846
msgid "Unable to launch USB Creator!"
msgstr ""

#: ../bin/testdrive-gtk.py:873
#, python-format
msgid " Downloading %s (0%%)"
msgstr ""

#: ../bin/testdrive-gtk.py:893
#, python-format
msgid " Downloading %s (%s%%)"
msgstr ""

#: ../bin/testdrive-gtk.py:896
#, python-format
msgid " Error downloading [%s]"
msgstr ""

#: ../bin/testdrive-gtk.py:946
#, python-format
msgid "Error preparing virtualization: %s"
msgstr ""

#: ../bin/testdrive-gtk.py:952
msgid "    Configuring Virtual Machine..."
msgstr ""

#: ../bin/testdrive-gtk.py:960
msgid "     Running Virtual Machine..."
msgstr ""

#: ../bin/testdrive-gtk.py:1024
msgid "Show debug messages"
msgstr ""

#: ../bin/testdrive-gtk.py:1028 ../bin/testdrive.py:202
msgid "print version and system data, and exit"
msgstr ""

#: ../bin/testdrive-gtk.py:1033
#, python-format
msgid "testdrive-gtk %s"
msgstr ""

#: ../bin/testdrive.py:52
msgid ""
"\n"
"Welcome to Testdrive!\n"
msgstr ""

#: ../bin/testdrive.py:60
#, python-format
msgid "     +-cache--> [%s] %s"
msgstr ""

#: ../bin/testdrive.py:63
#, python-format
msgid "  %d. Other (prompt for ISO URL)"
msgstr ""

#: ../bin/testdrive.py:65
msgid ""
"\n"
"Select an image to testdrive [1]: "
msgstr ""

#: ../bin/testdrive.py:74
msgid ""
"\n"
"ERROR: Invalid input\n"
msgstr ""

#: ../bin/testdrive.py:78
msgid ""
"\n"
"Enter an ISO URL to testdrive: "
msgstr ""

#: ../bin/testdrive.py:88
msgid ""
"\n"
"ERROR: Invalid selection\n"
msgstr ""

#: ../bin/testdrive.py:106 ../testdrivegtk/AddOtherTestdrivegtkDialog.py:155
#, python-format
msgid "Invalid ISO URL [%s]"
msgstr ""

#: ../bin/testdrive.py:148
#, python-format
msgid ""
"Command failed\n"
"    `%s`"
msgstr ""

#: ../bin/testdrive.py:155
msgid "Launching Virtual Machine using CURSES as screen mode"
msgstr ""

#: ../bin/testdrive.py:200
msgid "user configuration file (overriding default values"
msgstr ""

#: ../bin/testdrive.py:204
msgid "get ISO image from this URL location"
msgstr ""

#: ../bin/testdrive.py:206
msgid "try to launch usb-creator for further testing"
msgstr ""

#: ../bin/testdrive.py:208
msgid "hardcode Ubuntu RELEASE codename"
msgstr ""

#: ../bin/testdrive.py:210
msgid ""
"hardcode Ubuntu flavor. Available Flavors:\n"
"             ubuntu/kubuntu/xubuntu/edubuntu/mythbuntu/ubuntustudio/lubuntu/"
"ubuntukylin/ubuntugnome"
msgstr ""

#: ../bin/testdrive.py:213
msgid ""
"hardcode Ubuntu repository from where to obtain ISOs:\n"
"             releases/cdimage/cloud-daily/cloud-releases"
msgstr ""

#: ../bin/testdrive.py:216
msgid "displays the Virtual Machine in the shell. Only valid for Cloud images."
msgstr ""

#: ../bin/testdrive.py:221
#, python-format
msgid "version passed: %s"
msgstr ""

#: ../bin/testdrive.py:225
#, python-format
msgid "testdrive %s"
msgstr ""

#: ../bin/testdrive.py:237
#, python-format
msgid "config passed: %s"
msgstr ""

#: ../bin/testdrive.py:247
#, python-format
msgid "Trying config in %s"
msgstr ""

#: ../bin/testdrive.py:251
#, python-format
msgid "Using configuration in %s"
msgstr ""

#: ../bin/testdrive.py:253
#, python-format
msgid "Invalid configuration [%s]"
msgstr ""

#: ../bin/testdrive.py:261
msgid ""
"Your CPU supports KVM acceleration; please install KVM:\n"
"            sudo apt-get install qemu-kvm"
msgstr ""

#: ../bin/testdrive.py:264
msgid ""
"Your CPU does not support acceleration; run kvm-ok for more information; "
"then please install VirtualBox:\n"
"            kvm-ok\n"
"            sudo apt-get install virtualbox"
msgstr ""

#: ../bin/testdrive.py:288
msgid ""
"Launching Cloud images only works with KVM. Please switch your "
"virtualization method..."
msgstr ""

#: ../bin/testdrive.py:339
#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:351
#, python-format
msgid "Obtaining Ubuntu ISO list from %s..."
msgstr ""

#: ../bin/testdrive.py:343
#, python-format
msgid "ERROR: Could not obtain the Ubuntu ISO list from %s..."
msgstr ""

#: ../bin/testdrive.py:349
#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:363
msgid "Unable to update the Ubuntu ISO list cache..."
msgstr ""

#. BUG: should check disk space availability in CACHE dir
#. Update the cache
#: ../bin/testdrive.py:375
msgid "Syncing the specified ISO..."
msgstr ""

#: ../bin/testdrive.py:382 ../testdrivegtk/AddOtherTestdrivegtkDialog.py:167
#, python-format
msgid "ISO not found at [%s]"
msgstr ""

#. ##################
#. # Launch the VM ##
#. ##################
#: ../bin/testdrive.py:405
msgid "Validating Virtualization Method...."
msgstr ""

#: ../bin/testdrive.py:409
#, python-format
msgid "Unable to validate Virtualization Method [%s] (%s)"
msgstr ""

#: ../bin/testdrive.py:412
msgid "Setting up Virtual Machine..."
msgstr ""

#: ../bin/testdrive.py:416
#, python-format
msgid "Unable to setup Virtual Machine (%s)"
msgstr ""

#: ../bin/testdrive.py:418
msgid "Launching Virtual Machine..."
msgstr ""

#: ../bin/testdrive.py:426
#, python-format
msgid "Unable to launch Virtual Machine (%s)"
msgstr ""

#: ../bin/testdrive.py:430
#, python-format
msgid "Cleaning up disk image [%s]..."
msgstr ""

#. Remind about cache cleanup
#: ../bin/testdrive.py:433
msgid "You may wish to clean up the cache directory..."
msgstr ""

#: ../bin/testdrive.py:434
#, python-format
msgid "      %s and %s"
msgstr ""

#: ../bin/testdrive.py:441
msgid ""
"\n"
"Launch USB Startup Disk Creator for further testing of this ISO? [y/N] "
msgstr ""

#: ../bin/testdrive.py:445
msgid ""
"\n"
"Press <enter> to exit..."
msgstr ""

#: ../testdrivegtk/AddOtherTestdrivegtkDialog.py:135
msgid "Please insert a Description"
msgstr ""

#: ../testdrivegtk/AddOtherTestdrivegtkDialog.py:140
msgid "Please insert a URL"
msgstr ""

#: ../testdrivegtk/AddOtherTestdrivegtkDialog.py:171
msgid "No sync protocol has been selected, please select one."
msgstr ""

#: ../testdrivegtk/AddOtherTestdrivegtkDialog.py:196
msgid "Description"
msgstr ""

#: ../testdrivegtk/AddOtherTestdrivegtkDialog.py:227
msgid "Select Protocol:"
msgstr ""

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:36
#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:37
msgid "Other..."
msgstr ""

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:72
msgid "TestDrive Preferences"
msgstr ""

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:98
msgid "finish_initialization()"
msgstr ""

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:138
msgid "Select Repository:"
msgstr ""

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:149
#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:514
msgid "Select Release:"
msgstr ""

#. Load config files for local variables
#. self.load_config_files(file)
#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:223
#, python-format
msgid "Reading config file: [%s]"
msgstr ""

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:225
#, python-format
msgid "Unable to load config file [%s]"
msgstr ""

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:288
#, python-format
msgid " of %s available."
msgstr ""

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:355
#, python-format
msgid "Could not obtain the Ubuntu ISO list from %s..."
msgstr ""

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:359
msgid "Updating the Ubuntu ISO list cache..."
msgstr ""

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:367
msgid "get_preferences()"
msgstr ""

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:496
#, python-format
msgid "Unable to clean up files from [%s]"
msgstr ""
